### ISSUE TITLE
HTML report for viewing the baseline and actual image highlighting the difference

### ISSUE THREAD

**Issue by Sumit-Soman** [wswebcreation/webdriver-image-comparison#17]
Expecting a similar html report generated by jest-screenshot.
[jest-screenshot-report.zip](https://github.com/wswebcreation/webdriver-image-comparison/files/3207513/jest-screenshot-report.zip)

**Comment by wswebcreation** [comment]
???????

What do you mean? To be honest, I close this issue because I can't do anything with this. Please use the provided templates and file an issue / ask something about the docs / ask for a feature / ask a question (better to do that on Gitter)

**Comment by wswebcreation** [comment]
Hmm,

After looking into this I think I understand what you want. This is not something that will be supported by this module because it doesn't build a report based on images. Secondly the report and steps need to be different per used framework.
This module will only do the comparison for you and provide the paths to all the actual/baseline/diff images.

For next time, please follow the template and provide a decent description what the question / feature is. That will help me in looking into these issues in my spare time

**Comment by Sumit-Soman** [comment]
Sorry for this, it was something quick which i did.

**Comment by wswebcreation** [comment]
No problem,

I was also my fault, I shouldn't have responded like this.

**Comment by RubyGemTSL** [comment]
Hi @wswebcreation, you mentioned in your email that we should raise a feature request for this, so I asked Sumit to raise this. I think he assumed that you had more context which is why he didn't follow the template so I take responsibility for this :) 

So a report to compare baseline and actual is not going to be possible?

**Comment by wswebcreation** [comment]
Hi @RubyGemTSL 

Yeah, because I didn't had the context in this issue I didn't realise it was for you, sorry for that.

To answer the question, no, this module will not have a report like this because it is not tied to a specific framework (this core module can be used for WebdriverIO, Protractor, and what ever framework wants to use it) and not a specific testrunner (like Jasmine, CucumberJS, Mocha, Jest and so on)

I hope that makes it a little bit more clear
