### ISSUE TITLE
Expose browser version as a variable for formatImageName

### ISSUE THREAD

**Issue by iamkenos** [wswebcreation/webdriver-image-comparison#27]
**Is your feature request related to a problem? Please describe.**
Image rendering can vary between browser versions. It would be nice to have a direct way of including the browser version in the image name similar to the wdio4 vr service.

**Describe the solution you'd like**
To expose a `{browserVersion}` var that can be picked up by `formatImageName` option

**Describe alternatives you've considered**
`browser.capabilities.version`

**Comment by wswebcreation** [comment]
Hi @iamkenos 

Thanks for the feature request. I'll add that one into this module, but I need to check . how I can provide that in a good way for and the https://github.com/wswebcreation/wdio-image-comparison-service and the https://github.com/wswebcreation/protractor-image-comparison modules, because they both use this core.

**Comment by iamkenos** [comment]
I just realized there's already a feature request for this.
https://github.com/wswebcreation/webdriver-image-comparison/issues/6

I guess you can mark this one as dupe
