### ISSUE TITLE
How to test multiple viewports?

### ISSUE THREAD

**Issue by LukeLeber** [wswebcreation/webdriver-image-comparison#51]
I think that a suggested / recommended strategy for testing multiple viewports should be documented.

For example, are individual tests required to explicitly set the viewport dimensions prior to capturing a screenshot, or is there a more global option available that can assist in setting up global viewport dimensions?

Great job on this by the way!

**Comment by wswebcreation** [comment]
Hi @LukeLeber 

Thanks for filing an issue and asking for some more explanation. What this specific module does (and also the modules that use this comparison core) is take a screenshot of the current state of the screen/device. This means that if you want to take screenshots of different viewports, you need to adjust this **before** a screenshot is taken, meaning not by this module.

I also don't know where this should be documented because this module is only a core to do the comparison. Do you have a suggestion?

**Comment by LukeLeber** [comment]
Hi, I originally found this project via a blog post (https://webdriver.io/blog/2019/05/18/visual-regression-for-v5.html).  I'm thinking that any recommendations might make more sense to add to https://github.com/wswebcreation/wdio-image-comparison-service instead of this repository.

Perhaps the documentation for this repository could include a short blurb explaining the scope of what the core functionality covers.  I think that your quote above sums it up very nicely.

> ...if you want to take screenshots of different viewports, you need to adjust this before a screenshot is taken, meaning not by this module.

**Comment by wswebcreation** [comment]
OK, thanks. I'll add that on my todo list
